[package]
name = "solana_tx_decoding"
edition = "2024"

[dependencies]
solana_central = { path = "../solana_central" }
yellowstone-grpc-proto = "6.1.0"
solana-sdk = "2.2.2"
borsh = "1.5.7"
solana-storage-proto = "3.0.5"
tokio = "1.47.1"
